package com.peoplenet.qa.model;

// Generated Nov 4, 2015 10:37:05 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BaseConfig generated by hbm2java
 */
@Entity
@Table(name = "base_config")
public class BaseConfig implements java.io.Serializable {

	private static final long serialVersionUID = -4930369004140774708L;
	private BaseConfigId id;
	private String testResultsDir;
	private Boolean emailReports;
	private boolean remoteDriver;
	private String remoteUser;
	private String remoteKey;
	private Long timeWait;

	public BaseConfig() {
	}

	public BaseConfig(BaseConfig config) {
		this.id = config.getId();
		this.testResultsDir = config.getTestResultsDir();
		this.emailReports = config.getEmailReports();
		this.remoteDriver = config.isRemoteDriver();
		this.remoteUser = config.getRemoteUser();
		this.remoteKey = config.getRemoteKey();
		this.timeWait = config.getTimeWait();
	}

	public BaseConfig(BaseConfigId id, boolean remoteDriver, String remoteUser,
			String remoteKey) {
		this.id = id;
		this.remoteDriver = remoteDriver;
		this.remoteUser = remoteUser;
		this.remoteKey = remoteKey;
	}

	public BaseConfig(BaseConfigId id, String testResultsDir,
			Boolean emailReports, boolean remoteDriver, String remoteUser,
			String remoteKey, Long timeWait) {
		this.id = id;
		this.testResultsDir = testResultsDir;
		this.emailReports = emailReports;
		this.remoteDriver = remoteDriver;
		this.remoteUser = remoteUser;
		this.remoteKey = remoteKey;
		this.timeWait = timeWait;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "project", column = @Column(name = "project", nullable = false)),
			@AttributeOverride(name = "environment", column = @Column(name = "environment", nullable = false)),
			@AttributeOverride(name = "buildVersion", column = @Column(name = "buildVersion", nullable = false)) })
	public BaseConfigId getId() {
		return this.id;
	}

	public void setId(BaseConfigId id) {
		this.id = id;
	}

	@Column(name = "testResultsDir")
	public String getTestResultsDir() {
		return this.testResultsDir;
	}

	public void setTestResultsDir(String testResultsDir) {
		this.testResultsDir = testResultsDir;
	}

	@Column(name = "emailReports")
	public Boolean getEmailReports() {
		return this.emailReports;
	}

	public void setEmailReports(Boolean emailReports) {
		this.emailReports = emailReports;
	}

	@Column(name = "remoteDriver", nullable = false)
	public boolean isRemoteDriver() {
		return this.remoteDriver;
	}

	public void setRemoteDriver(boolean remoteDriver) {
		this.remoteDriver = remoteDriver;
	}

	@Column(name = "remoteUser")
	public String getRemoteUser() {
		return this.remoteUser;
	}

	public void setRemoteUser(String remoteUser) {
		this.remoteUser = remoteUser;
	}

	@Column(name = "remoteKey")
	public String getRemoteKey() {
		return this.remoteKey;
	}

	public void setRemoteKey(String remoteKey) {
		this.remoteKey = remoteKey;
	}

	@Column(name = "timeWait")
	public Long getTimeWait() {
		return this.timeWait;
	}

	public void setTimeWait(Long timeWait) {
		this.timeWait = timeWait;
	}

}
