package com.peoplenet.qa.model;

// Generated Nov 5, 2015 10:41:55 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DataConfig generated by hbm2java
 */
@Entity
@Table(name = "data_config", uniqueConstraints = @UniqueConstraint(columnNames = {
		"project", "buildVersion", "environment", "userType", "browser",
		"mobileView" }))
public class DataConfig implements java.io.Serializable {

	private static final long serialVersionUID = -8780453428988425212L;
	private Long id;
	private String project;
	private String environment;
	private String buildVersion;
	private String userType;
	private String browser;
	private String browserVersion;
	private Boolean mobileView;
	private String scriptName;
	private Boolean status;
	private String description;

	public DataConfig() {
	}

	public DataConfig(String project, String environment, String buildVersion,
			String userType, String browser, String browserVersion,
			String scriptName) {
		this.project = project;
		this.environment = environment;
		this.buildVersion = buildVersion;
		this.userType = userType;
		this.browser = browser;
		this.browserVersion = browserVersion;
		this.scriptName = scriptName;
	}

	public DataConfig(String project, String environment, String buildVersion,
			String userType, String browser, String browserVersion,
			Boolean mobileView, String scriptName, Boolean status,
			String description) {
		this.project = project;
		this.environment = environment;
		this.buildVersion = buildVersion;
		this.userType = userType;
		this.browser = browser;
		this.browserVersion = browserVersion;
		this.mobileView = mobileView;
		this.scriptName = scriptName;
		this.status = status;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "project", nullable = false)
	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "environment", nullable = false)
	public String getEnvironment() {
		return this.environment;
	}

	public void setEnvironment(String environment) {
		this.environment = environment;
	}

	@Column(name = "buildVersion", nullable = false)
	public String getBuildVersion() {
		return this.buildVersion;
	}

	public void setBuildVersion(String buildVersion) {
		this.buildVersion = buildVersion;
	}

	@Column(name = "userType", nullable = false)
	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "browser", nullable = false)
	public String getBrowser() {
		return this.browser;
	}

	public void setBrowser(String browser) {
		this.browser = browser;
	}

	@Column(name = "browserVersion")
	public String getBrowserVersion() {
		return this.browserVersion;
	}

	public void setBrowserVersion(String browserVersion) {
		this.browserVersion = browserVersion;
	}

	@Column(name = "mobileView")
	public Boolean getMobileView() {
		return this.mobileView;
	}

	public void setMobileView(Boolean mobileView) {
		this.mobileView = mobileView;
	}

	@Column(name = "scriptName", nullable = false)
	public String getScriptName() {
		return this.scriptName;
	}

	public void setScriptName(String scriptName) {
		this.scriptName = scriptName;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
