package com.peoplenet.qa.model;

// Generated Nov 16, 2015 11:57:01 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InputConfig generated by hbm2java
 */
@Entity
@Table(name = "input_config")
public class InputConfig implements java.io.Serializable {

	private static final long serialVersionUID = 3873697544033388394L;
	private Long id;
	private String scriptName;
	private String project;
	private String environment;
	private String version;
	private String client;
	private String group;
	private String site;
	private String lastSsn;
	private String firstName;
	private String lastName;
	private String empId;
	private String empEmail;
	private String empPassword;
	private String empType;
	private String apprFirstName;
	private String apprLastName;
	private String apprEmail;
	private String inTime;
	private String outTime;
	private String time;
	private String projectHours;
	private String projectCount;
	private String workCount;
	private String breaksCount;
	private String udfValue;
	private Boolean addProject;
	private Boolean addAssignments;
	private Boolean deleteAssignments;
	private String assignmentName;
	private Boolean addComment;
	private Boolean addAttachment;
	private Boolean showOt;
	private String timeEntryMethod;
	private String action;
	private String addEmployee;
	private String processEmployee;
	private String processFromTmc;
	private Boolean checkTmc;
	private Boolean approveFromTmc;
	private Boolean deleteFromTmc;
	private String addWebClient;
	private String clientCode;
	private String clientName;
	private String addBranch;
	private String groupCode;
	private String groupName;
	private String weeklyHq;
	private String menuFunction;
	private String menuAction;
	private String addRole;
	private String roleName;

	public InputConfig() {
	}

	public InputConfig(String scriptName, String project, String environment,
			String version, String client, String group, String site,
			String empEmail, String empPassword) {
		this.scriptName = scriptName;
		this.project = project;
		this.environment = environment;
		this.version = version;
		this.client = client;
		this.group = group;
		this.site = site;
		this.empEmail = empEmail;
		this.empPassword = empPassword;
	}

	public InputConfig(String scriptName, String project, String environment,
			String version, String client, String group, String site,
			String lastSsn, String firstName, String lastName, String empId,
			String empEmail, String empPassword, String empType,
			String apprFirstName, String apprLastName, String apprEmail,
			String inTime, String outTime, String time, String projectHours,
			String projectCount, String workCount, String breaksCount,
			String udfValue, Boolean addProject, Boolean addAssignments,
			Boolean deleteAssignments, String assignmentName,
			Boolean addComment, Boolean addAttachment, Boolean showOt,
			String timeEntryMethod, String action, String addEmployee,
			String processEmployee, String processFromTmc, Boolean checkTmc,
			Boolean approveFromTmc, Boolean deleteFromTmc, String addWebClient,
			String clientCode, String clientName, String addBranch,
			String groupCode, String groupName, String weeklyHq,
			String menuFunction, String menuAction, String addRole,
			String roleName) {
		this.scriptName = scriptName;
		this.project = project;
		this.environment = environment;
		this.version = version;
		this.client = client;
		this.group = group;
		this.site = site;
		this.lastSsn = lastSsn;
		this.firstName = firstName;
		this.lastName = lastName;
		this.empId = empId;
		this.empEmail = empEmail;
		this.empPassword = empPassword;
		this.empType = empType;
		this.apprFirstName = apprFirstName;
		this.apprLastName = apprLastName;
		this.apprEmail = apprEmail;
		this.inTime = inTime;
		this.outTime = outTime;
		this.time = time;
		this.projectHours = projectHours;
		this.projectCount = projectCount;
		this.workCount = workCount;
		this.breaksCount = breaksCount;
		this.udfValue = udfValue;
		this.addProject = addProject;
		this.addAssignments = addAssignments;
		this.deleteAssignments = deleteAssignments;
		this.assignmentName = assignmentName;
		this.addComment = addComment;
		this.addAttachment = addAttachment;
		this.showOt = showOt;
		this.timeEntryMethod = timeEntryMethod;
		this.action = action;
		this.addEmployee = addEmployee;
		this.processEmployee = processEmployee;
		this.processFromTmc = processFromTmc;
		this.checkTmc = checkTmc;
		this.approveFromTmc = approveFromTmc;
		this.deleteFromTmc = deleteFromTmc;
		this.addWebClient = addWebClient;
		this.clientCode = clientCode;
		this.clientName = clientName;
		this.addBranch = addBranch;
		this.groupCode = groupCode;
		this.groupName = groupName;
		this.weeklyHq = weeklyHq;
		this.menuFunction = menuFunction;
		this.menuAction = menuAction;
		this.addRole = addRole;
		this.roleName = roleName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "scriptName", nullable = false)
	public String getScriptName() {
		return this.scriptName;
	}

	public void setScriptName(String scriptName) {
		this.scriptName = scriptName;
	}

	@Column(name = "project", nullable = false)
	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "environment", nullable = false)
	public String getEnvironment() {
		return this.environment;
	}

	public void setEnvironment(String environment) {
		this.environment = environment;
	}

	@Column(name = "version", nullable = false)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "client", nullable = false)
	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	@Column(name = "group", nullable = false)
	public String getGroup() {
		return this.group;
	}

	public void setGroup(String group) {
		this.group = group;
	}

	@Column(name = "site", nullable = false)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "lastSSN", nullable = true)
	public String getLastSsn() {
		return this.lastSsn;
	}

	public void setLastSsn(String lastSsn) {
		this.lastSsn = lastSsn;
	}

	@Column(name = "firstName", nullable = true)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = true)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "empId", nullable = true)
	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	@Column(name = "empEmail", nullable = false)
	public String getEmpEmail() {
		return this.empEmail;
	}

	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail;
	}

	@Column(name = "empPassword", nullable = false)
	public String getEmpPassword() {
		return this.empPassword;
	}

	public void setEmpPassword(String empPassword) {
		this.empPassword = empPassword;
	}

	@Column(name = "empType", nullable = true)
	public String getEmpType() {
		return this.empType;
	}

	public void setEmpType(String empType) {
		this.empType = empType;
	}

	@Column(name = "apprFirstName", nullable = true)
	public String getApprFirstName() {
		return this.apprFirstName;
	}

	public void setApprFirstName(String apprFirstName) {
		this.apprFirstName = apprFirstName;
	}

	@Column(name = "apprLastName", nullable = true)
	public String getApprLastName() {
		return this.apprLastName;
	}

	public void setApprLastName(String apprLastName) {
		this.apprLastName = apprLastName;
	}

	@Column(name = "apprEmail", nullable = true)
	public String getApprEmail() {
		return this.apprEmail;
	}

	public void setApprEmail(String apprEmail) {
		this.apprEmail = apprEmail;
	}

	@Column(name = "inTime", nullable = true)
	public String getInTime() {
		return this.inTime;
	}

	public void setInTime(String inTime) {
		this.inTime = inTime;
	}

	@Column(name = "outTime", nullable = true)
	public String getOutTime() {
		return this.outTime;
	}

	public void setOutTime(String outTime) {
		this.outTime = outTime;
	}

	@Column(name = "time", nullable = true)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "projectHours", nullable = true)
	public String getProjectHours() {
		return this.projectHours;
	}

	public void setProjectHours(String projectHours) {
		this.projectHours = projectHours;
	}

	@Column(name = "projectCount", nullable = true)
	public String getProjectCount() {
		return this.projectCount;
	}

	public void setProjectCount(String projectCount) {
		this.projectCount = projectCount;
	}

	@Column(name = "workCount", nullable = true)
	public String getWorkCount() {
		return this.workCount;
	}

	public void setWorkCount(String workCount) {
		this.workCount = workCount;
	}

	@Column(name = "breaksCount", nullable = true)
	public String getBreaksCount() {
		return this.breaksCount;
	}

	public void setBreaksCount(String breaksCount) {
		this.breaksCount = breaksCount;
	}

	@Column(name = "udfValue", nullable = true)
	public String getUdfValue() {
		return this.udfValue;
	}

	public void setUdfValue(String udfValue) {
		this.udfValue = udfValue;
	}

	@Column(name = "addProject", nullable = true)
	public Boolean getAddProject() {
		return this.addProject;
	}

	public void setAddProject(Boolean addProject) {
		this.addProject = addProject;
	}

	@Column(name = "addAssignments", nullable = true)
	public Boolean getAddAssignments() {
		return this.addAssignments;
	}

	public void setAddAssignments(Boolean addAssignments) {
		this.addAssignments = addAssignments;
	}

	@Column(name = "deleteAssignments", nullable = true)
	public Boolean getDeleteAssignments() {
		return this.deleteAssignments;
	}

	public void setDeleteAssignments(Boolean deleteAssignments) {
		this.deleteAssignments = deleteAssignments;
	}

	@Column(name = "assignmentName", nullable = true)
	public String getAssignmentName() {
		return this.assignmentName;
	}

	public void setAssignmentName(String assignmentName) {
		this.assignmentName = assignmentName;
	}

	@Column(name = "addComment", nullable = true)
	public Boolean getAddComment() {
		return this.addComment;
	}

	public void setAddComment(Boolean addComment) {
		this.addComment = addComment;
	}

	@Column(name = "addAttachment", nullable = true)
	public Boolean getAddAttachment() {
		return this.addAttachment;
	}

	public void setAddAttachment(Boolean addAttachment) {
		this.addAttachment = addAttachment;
	}

	@Column(name = "showOT", nullable = true)
	public Boolean getShowOt() {
		return this.showOt;
	}

	public void setShowOt(Boolean showOt) {
		this.showOt = showOt;
	}

	@Column(name = "timeEntryMethod", nullable = true)
	public String getTimeEntryMethod() {
		return this.timeEntryMethod;
	}

	public void setTimeEntryMethod(String timeEntryMethod) {
		this.timeEntryMethod = timeEntryMethod;
	}

	@Column(name = "action", nullable = true)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "addEmployee", nullable = true)
	public String getAddEmployee() {
		return this.addEmployee;
	}

	public void setAddEmployee(String addEmployee) {
		this.addEmployee = addEmployee;
	}

	@Column(name = "processEmployee", nullable = true)
	public String getProcessEmployee() {
		return this.processEmployee;
	}

	public void setProcessEmployee(String processEmployee) {
		this.processEmployee = processEmployee;
	}

	@Column(name = "processFromTMC", nullable = true)
	public String getProcessFromTmc() {
		return this.processFromTmc;
	}

	public void setProcessFromTmc(String processFromTmc) {
		this.processFromTmc = processFromTmc;
	}

	@Column(name = "checkTMC", nullable = true)
	public Boolean getCheckTmc() {
		return this.checkTmc;
	}

	public void setCheckTmc(Boolean checkTmc) {
		this.checkTmc = checkTmc;
	}

	@Column(name = "approveFromTMC", nullable = true)
	public Boolean getApproveFromTmc() {
		return this.approveFromTmc;
	}

	public void setApproveFromTmc(Boolean approveFromTmc) {
		this.approveFromTmc = approveFromTmc;
	}

	@Column(name = "deleteFromTMC", nullable = true)
	public Boolean getDeleteFromTmc() {
		return this.deleteFromTmc;
	}

	public void setDeleteFromTmc(Boolean deleteFromTmc) {
		this.deleteFromTmc = deleteFromTmc;
	}

	@Column(name = "addWebClient", nullable = true)
	public String getAddWebClient() {
		return this.addWebClient;
	}

	public void setAddWebClient(String addWebClient) {
		this.addWebClient = addWebClient;
	}

	@Column(name = "ClientCode", nullable = true)
	public String getClientCode() {
		return this.clientCode;
	}

	public void setClientCode(String clientCode) {
		this.clientCode = clientCode;
	}

	@Column(name = "ClientName", nullable = true)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "addBranch", nullable = true)
	public String getAddBranch() {
		return this.addBranch;
	}

	public void setAddBranch(String addBranch) {
		this.addBranch = addBranch;
	}

	@Column(name = "GroupCode", nullable = true)
	public String getGroupCode() {
		return this.groupCode;
	}

	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	@Column(name = "GroupName", nullable = true)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "WeeklyHQ", nullable = true)
	public String getWeeklyHq() {
		return this.weeklyHq;
	}

	public void setWeeklyHq(String weeklyHq) {
		this.weeklyHq = weeklyHq;
	}

	@Column(name = "menuFunction", nullable = true)
	public String getMenuFunction() {
		return this.menuFunction;
	}

	public void setMenuFunction(String menuFunction) {
		this.menuFunction = menuFunction;
	}

	@Column(name = "menuAction", nullable = true)
	public String getMenuAction() {
		return this.menuAction;
	}

	public void setMenuAction(String menuAction) {
		this.menuAction = menuAction;
	}

	@Column(name = "addRole", nullable = true)
	public String getAddRole() {
		return this.addRole;
	}

	public void setAddRole(String addRole) {
		this.addRole = addRole;
	}

	@Column(name = "roleName", nullable = true)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}
