package com.peoplenet.qa.model;

// Generated Nov 4, 2015 10:37:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MailConfig generated by hbm2java
 */
@Entity
@Table(name = "mail_config", uniqueConstraints = @UniqueConstraint(columnNames = {
		"mailType", "project", "environment", "buildVersion" }))
public class MailConfig implements java.io.Serializable {

	private static final long serialVersionUID = -2736958366391068173L;
	private String buildVersion;
	private String mailType;
	private String project;
	private String environment;
	private String mailFrom;
	private String mailPassword;
	private String mailTo;
	private String mailHost;
	private long mailPort;
	private String mailSubject;

	public MailConfig() {
	}

	public MailConfig(MailConfig config) {
		this.buildVersion = config.getBuildVersion();
		this.mailType = config.getMailType();
		this.project = config.getProject();
		this.environment = config.getEnvironment();
		this.mailFrom = config.getMailFrom();
		this.mailPassword = config.getMailPassword();
		this.mailTo = config.getMailTo();
		this.mailHost = config.getMailHost();
		this.mailPort = config.getMailPort();
	}

	public MailConfig(String buildVersion, String mailType, String project,
			String environment, String mailFrom, String mailPassword,
			String mailTo, String mailHost, long mailPort) {
		this.buildVersion = buildVersion;
		this.mailType = mailType;
		this.project = project;
		this.environment = environment;
		this.mailFrom = mailFrom;
		this.mailPassword = mailPassword;
		this.mailTo = mailTo;
		this.mailHost = mailHost;
		this.mailPort = mailPort;
	}

	public MailConfig(String buildVersion, String mailType, String project,
			String environment, String mailFrom, String mailPassword,
			String mailTo, String mailHost, long mailPort, String mailSubject) {
		this.buildVersion = buildVersion;
		this.mailType = mailType;
		this.project = project;
		this.environment = environment;
		this.mailFrom = mailFrom;
		this.mailPassword = mailPassword;
		this.mailTo = mailTo;
		this.mailHost = mailHost;
		this.mailPort = mailPort;
		this.mailSubject = mailSubject;
	}

	@Id
	@Column(name = "buildVersion", unique = true, nullable = false)
	public String getBuildVersion() {
		return this.buildVersion;
	}

	public void setBuildVersion(String buildVersion) {
		this.buildVersion = buildVersion;
	}

	@Column(name = "mailType", nullable = false)
	public String getMailType() {
		return this.mailType;
	}

	public void setMailType(String mailType) {
		this.mailType = mailType;
	}

	@Column(name = "project", nullable = false)
	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "environment", nullable = false)
	public String getEnvironment() {
		return this.environment;
	}

	public void setEnvironment(String environment) {
		this.environment = environment;
	}

	@Column(name = "mailFrom", nullable = false)
	public String getMailFrom() {
		return this.mailFrom;
	}

	public void setMailFrom(String mailFrom) {
		this.mailFrom = mailFrom;
	}

	@Column(name = "mailPassword", nullable = false)
	public String getMailPassword() {
		return this.mailPassword;
	}

	public void setMailPassword(String mailPassword) {
		this.mailPassword = mailPassword;
	}

	@Column(name = "mailTo", nullable = false)
	public String getMailTo() {
		return this.mailTo;
	}

	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}

	@Column(name = "mailHost", nullable = false)
	public String getMailHost() {
		return this.mailHost;
	}

	public void setMailHost(String mailHost) {
		this.mailHost = mailHost;
	}

	@Column(name = "mailPort", nullable = false)
	public long getMailPort() {
		return this.mailPort;
	}

	public void setMailPort(long mailPort) {
		this.mailPort = mailPort;
	}

	@Column(name = "mailSubject")
	public String getMailSubject() {
		return this.mailSubject;
	}

	public void setMailSubject(String mailSubject) {
		this.mailSubject = mailSubject;
	}

}
