package com.peoplenet.qa.model;

// Generated Nov 10, 2015 10:56:07 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MobileConfig generated by hbm2java
 */
@Entity
@Table(name = "mobile_config")
public class MobileConfig implements java.io.Serializable {

	private static final long serialVersionUID = 2417758609227390465L;
	private Long id;
	private String deviceName;
	private String platform;
	private String project;
	private String environment;
	private String buildVersion;

	public MobileConfig() {
	}

	public MobileConfig(String project, String environment,
			String buildVersion, String deviceName, String platform) {
		this.deviceName = deviceName;
		this.platform = platform;
		this.project = project;
		this.environment = environment;
		this.buildVersion = buildVersion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "deviceName", nullable = false)
	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	@Column(name = "platform", nullable = false)
	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@Column(name = "project", nullable = false)
	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "environment", nullable = false)
	public String getEnvironment() {
		return this.environment;
	}

	public void setEnvironment(String environment) {
		this.environment = environment;
	}

	@Column(name = "buildVersion", nullable = false)
	public String getBuildVersion() {
		return this.buildVersion;
	}

	public void setBuildVersion(String buildVersion) {
		this.buildVersion = buildVersion;
	}

}
